import Head from 'next/head'
import ContactsFooter from '../components/ContactsFooter';
import styles from '../styles/About.module.css'

export default function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>IVCMR-21 | About</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>hello world</p>
      </main>

      <footer className={styles.footer}>
        <ContactsFooter />
      </footer>
    </div>
  );
}