import Head from 'next/head'
import styles from '../styles/Home.module.css'
import AboutConference from '../components/AboutConference'
import ImportandDates from '../components/ImportantDates'
import SplashScreen from '../components/SplashScreen'
import KeynoteSpeakers from '../components/KeynoteSpeakers'
import TopicToBeCovered from '../components/TopicToBeCovered'
import DownloadsSection from '../components/DownloadsSection'

/*
 *  Layout:
 *    🟨 (need to add buttons) Welcome splash -> submit abstract, register now buttons
 *    ✅ About the conference [text block]
 *    🟨 Keynote speakers [profile cards] -> clickable profile for more info on person/talk
 *    ✅ important dates [date cards] -> could improve cards by adding logo
 *    ✅ topics to be covered
 *    ✅ downloads
 *    contacts
 * about page:
 *    about the college
 *    about the department
 * schedule:
 *
 */
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <SplashScreen />
        <AboutConference />
        <KeynoteSpeakers />
        <ImportandDates />
        <TopicToBeCovered />
        <DownloadsSection  />
      </main>

      <footer className={styles.footer}>
        Footer goes here
      </footer>
    </div>
  )
}
