import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import AboutConference from '../components/AboutConference'
import ImportandDates from '../components/ImportantDates'
import SplashScreen from '../components/SplashScreen'

/*
 *  Layout:
 *    ~-(need to add buttons) Welcome splash -> submit abstract, register now buttons
 *    -About the conference [text block]
 *    Keynote speakers [profile cards]
 *    -important dates [date cards]
 *    *insert something low density here*
 *    topics to be covered
 *    downloads
 *    contacts
 * about page:
 *    about the college
 *    about the department
 * schedule:
 *
 */
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <SplashScreen />
        <AboutConference />
        <ImportandDates />
      </main>

      <footer className={styles.footer}>
        Footer goes here
      </footer>
    </div>
  )
}
